Whitelists:
  axe:
    - "#mineable/axe"
    - "#leaves"
    - "!BARREL"
    - "!CHEST"
    - "!TRAPPED_CHEST"
    - "!#all_signs"
  pickaxe:
    - "#mineable/pickaxe"
    - "!SPAWNER"
    - "!GILDED_BLACKSTONE"
    - "!DROPPER"
    - "!DISPENSER"
    - "!HOPPER"
    - "!FURNACE"
    - "!BLAST_FURNACE"
    - "!SMOKER"
    - "!#shulker_boxes"
  shovel:
    "#mineable/shovel"
Commands:
  BlockCycle:
    Enabled: true
    Aliases: []
  BlockGravity:
    Enabled: true
    Aliases: []
  BoneMealBlock:
    Enabled: true
    Aliases: []
  BreakAndReplant:
    Enabled: true
    Aliases: []
  BreakInFacing:
    Enabled: true
    Aliases: []
  BreakInRadius:
    Enabled: true
    Aliases: []
  BreakInXYZ:
    Enabled: true
    Aliases: []
  BroadcastMessage:
    Enabled: true
    Aliases: []
  ChanceRandomRun:
    Enabled: true
    Aliases: []
  ChangeVillagerProfession:
    Enabled: true
    Aliases: []
  CobwebPrison:
    Enabled: true
    Aliases: []
#Recommended to not change unless you know what your doing
CommandNamespace: "commandutils"