Whitelists:
  axe:
    - "#mineable/axe"
    - "#leaves"
    - "!BARREL"
    - "!CHEST"
    - "!TRAPPED_CHEST"
    - "!#all_signs"
  pickaxe:
    - "#mineable/pickaxe"
    - "!SPAWNER"
    - "!GILDED_BLACKSTONE"
    - "!DROPPER"
    - "!DISPENSER"
    - "!HOPPER"
    - "!FURNACE"
    - "!BLAST_FURNACE"
    - "!SMOKER"
    - "!#shulker_boxes"
  shovel:
    "#mineable/shovel"
Commands:
  BlockCycle:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.blockcyclecommand"
    oxidize:
      KeepStairData: true
      KeepSlabData: true
      blocks:
        - CUT_COPPER_STAIRS EXPOSED_CUT_COPPER_STAIRS
        - EXPOSED_CUT_COPPER_STAIRS WEATHERED_CUT_COPPER_STAIRS
        - WEATHERED_CUT_COPPER_STAIRS OXIDIZED_CUT_COPPER_STAIRS
        - OXIDIZED_CUT_COPPER_STAIRS CUT_COPPER_STAIRS
        - WAXED_CUT_COPPER_STAIRS WAXED_EXPOSED_CUT_COPPER_STAIRS
        - WAXED_EXPOSED_CUT_COPPER_STAIRS WAXED_WEATHERED_CUT_COPPER_STAIRS
        - WAXED_WEATHERED_CUT_COPPER_STAIRS WAXED_OXIDIZED_CUT_COPPER_STAIRS
        - WAXED_OXIDIZED_CUT_COPPER_STAIRS WAXED_CUT_COPPER_STAIRS
  BlockGravity:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.blockgravitycommand"

  BoneMealBlock:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.bonemealblockcommand"

  BreakAndReplant:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakandreplantcommand"

  BreakInFacing:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinfacingcommand"

  BreakInRadius:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinradiuscommand"

  BreakInXYZ:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinxyzcommand"

  BroadcastMessage:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.broadcastmessagecommand"

  ChanceRandomRun:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.chancerandomruncommand"

  ChangeVillagerProfession:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.changevillagerprofessioncommand"

  CobwebPrison:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.cobwebprisoncommand"

  Food:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.foodcommand"

  God:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.godcommand"

  HighlightBlocks:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.highlightblockscommand"

  ItemAttribute:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.itemattributecommand"

  LaunchDragonFireball:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.launchdragonfireballcommand"

  LaunchFirework:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.launchfireworkcommand"

  LoadCrossbow:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.loadcrossbowcommand"

  PushEntity:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.pushentitycommand"

  RayTraceParticle:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.raytraceparticlecommand"

  RemoveItemSetVariable:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.removeitemsetvariablecommand"

  ReplaceInFacing:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.replaceinfacingcommand"

  RunCommandLater:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.runcommandlatercommand"

  RunCommandWhen:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.runcommandwhencommand"

  SendBossBar:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.sendbossbarcommand"

  SendMessage:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.sendmessagecommand"

  SetCursorItem:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.setcursoritemcommand"

  SetItem:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.setitemcommand"

  SetItemNBT:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.setitemnbtcommand"

  SetTNTSource:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.settntsourcecommand"

  SilentParticle:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.silentparticlecommand"

  SpawnBlockBreaker:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.spawnblockbreakercommand"

  SpawnNoDamageEvokerFang:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.spawnnodamageevokerfangcommand"

  SpawnNoDamageFirework:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.spawnnodamagefireworkcommand"

  Waterlog:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.waterlogcommand"

  WeightedRandom:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.weightedrandomcommand"

  While:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.whilecommand"

#Recommended to not change unless you know what your doing
CommandNamespace: "commandutils"