Whitelists:
  axe:
    - "#mineable/axe"
    - "#leaves"
    - "!BARREL"
    - "!CHEST"
    - "!TRAPPED_CHEST"
    - "!#all_signs"
  pickaxe:
    - "#mineable/pickaxe"
    - "!SPAWNER"
    - "!GILDED_BLACKSTONE"
    - "!DROPPER"
    - "!DISPENSER"
    - "!HOPPER"
    - "!FURNACE"
    - "!BLAST_FURNACE"
    - "!SMOKER"
    - "!#shulker_boxes"
  shovel:
    "#mineable/shovel"
Placeholders:
  Enabled: true
  StringUtils:
    Enabled: true
    ArgumentSeparator: ","
    AllowCustomSeparator: true
    If:
      ElseIfKeyword: "elseif"
      ElseKeyword: "else"
      ConditionSeparator: "\""
  InvUtils:
    Enabled: true
    FunctionSeparator: "_"
    AllowCustomSeparator: true
    Nbt:
      ArgsSeparator: ","
    Amount:
      ArgsSeparator: ","

Commands:
  BlockCycle:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.blockcyclecommand"
    oxidize:
      KeepStairData: true
      KeepSlabData: true
      blocks:
        - CUT_COPPER_STAIRS EXPOSED_CUT_COPPER_STAIRS
        - EXPOSED_CUT_COPPER_STAIRS WEATHERED_CUT_COPPER_STAIRS
        - WEATHERED_CUT_COPPER_STAIRS OXIDIZED_CUT_COPPER_STAIRS
        - OXIDIZED_CUT_COPPER_STAIRS CUT_COPPER_STAIRS
        - WAXED_CUT_COPPER_STAIRS WAXED_EXPOSED_CUT_COPPER_STAIRS
        - WAXED_EXPOSED_CUT_COPPER_STAIRS WAXED_WEATHERED_CUT_COPPER_STAIRS
        - WAXED_WEATHERED_CUT_COPPER_STAIRS WAXED_OXIDIZED_CUT_COPPER_STAIRS
        - WAXED_OXIDIZED_CUT_COPPER_STAIRS WAXED_CUT_COPPER_STAIRS
  BlockGravity:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.blockgravitycommand"

  BoneMealBlock:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.bonemealblockcommand"

  BreakAndReplant:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakandreplantcommand"

  BreakInFacing:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinfacingcommand"

  BreakInRadius:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinradiuscommand"

  BreakInXYZ:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinxyzcommand"

  BroadcastMessage:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.broadcastmessagecommand"

  ChanceRandomRun:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.chancerandomruncommand"
    ArgumentSeparator: ",,"
    CommandSeparator: "\\|"

  ChangeVillagerProfession:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.changevillagerprofessioncommand"

  CobwebPrison:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.cobwebprisoncommand"

  Food:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.foodcommand"

  God:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.godcommand"

  HighlightBlocks:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.highlightblockscommand"
    DefaultParticle: "ELECTRIC_SPARK"
    DefaultParticleOffset: 0.0
    DefaultParticleSpeed: 0.0
    DefaultParticleCount: 1
    DefaultNumberOfIntervals: 40
    DefaultParticleSpawnInterval: 2

  If:
    Enabled: true
    Aliases: []
    ElseIfKeyword: "elseif"
    ElseKeyword: "else"
    CommandSeparator: ",,"
    ConditionSeparator: "\""

  ItemAttribute:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.itemattributecommand"

  LaunchDragonFireball:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.launchdragonfireballcommand"

  LaunchFirework:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.launchfireworkcommand"

  LoadCrossbow:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.loadcrossbowcommand"

  ParsePlaceholder:
    Enabled: true
    Aliases: []

  PushEntity:
    Enabled: true
    Aliases: []

  RayTraceParticle:
    Enabled: true
    Aliases: []

  RemoveItem:
    Enabled: true
    Aliases: []
    CommandSeparator: ","

  ReplaceInFacing:
    Enabled: true
    Aliases: []

  RunCommandLater:
    Enabled: true
    Aliases: []

  RunCommandWhen:
    Enabled: true
    Aliases: []

  SendBossBar:
    Enabled: true
    Aliases: []

  SendMessage:
    Enabled: true
    Aliases: []
    Use&ForColorCodesByDefault: true
    ParsePlaceholdersByDefault: true
    ColorCodesByDefault: true
    PlayersListArg: false

  SetCursorItem:
    Enabled: true
    Aliases: []

  SetItem:
    Enabled: true
    Aliases: []

  SetItemNBT:
    Enabled: true
    Aliases: []

  SetTNTSource:
    Enabled: true
    Aliases: []
    #Allow selecting multiple tnt's at once to set source, requires restart
    MultipleTNTs: true
    #Allow selecting multiple sources at once, will be a random source if more than one source is provided, requires restart
    MultipleSources: false
  SilentParticle:
    Enabled: true
    Aliases: []

  SpawnBlockBreaker:
    Enabled: true
    Aliases: []

  SpawnNoDamageEvokerFang:
    Enabled: true
    Aliases: []

  SpawnNoDamageFirework:
    Enabled: true
    Aliases: []

  Waterlog:
    Enabled: true
    Aliases: []

  WeightedRandom:
    Enabled: true
    Aliases: []
    ArgumentSeparator: ",,"
    CommandSeparator: "\\|"


  While:
    Enabled: true
    Aliases: []
    CommandSeparator: "\\|"
    PlaceholderSurrounder: "$"

#Recommended to not change unless you know what your doing
CommandNamespace: "commandutils"