name: CommandUtils
version: '2.5.0'
main: me.dunescifye.commandutils.CommandUtils
softdepend: [PlaceholderAPI, GriefPrevention, ExecutableBlocks, CoreProtect, Factions, LibsDisguises]
api-version: '1.21'